'''Describes how treasures in vanilla mode differ from standard mode.'''
from __future__ import annotations

import ctenums
from treasures import treasuredata


def get_vanilla_treasure_tiers() -> dict[treasuredata.TreasureLocTier,
                                         list[ctenums.TreasureID]]:
    '''
    Return a dictionary associating tier with a list of treasures in that tier.
    '''
    TID = ctenums.TreasureID
    td = treasuredata

    ret_dict: dict[td.TreasureLocTier, list[ctenums.TreasureID]] = {
        tier: []
        for tier in td.TreasureLocTier
    }

    # Recall Progression is Cath, Trial, Early Future, Heckran,
    # Denadoro, Reptite, Magus, Tyrano, Woe, Ocean Palace, Sidequests, Omen

    # Low = Open, Cath
    # LowMid = Trial, Early Future, Heckran
    # Mid = Denadoro, Repite, Magus, Tyrano
    # MidHigh = Woe, Ocean Palace, SideQuests
    # HighAwe = Omen

    ret_dict[td.TreasureLocTier.LOW] = [
        TID.TRUCE_MAYOR_1F, TID.TRUCE_MAYOR_2F, TID.KINGS_ROOM_1000,
        TID.QUEENS_ROOM_1000, TID.FOREST_RUINS, TID.PORRE_MAYOR_2F,
        TID.TRUCE_CANYON_1, TID.TRUCE_CANYON_2, TID.KINGS_ROOM_600,
        TID.QUEENS_ROOM_600, TID.ROYAL_KITCHEN, TID.CURSED_WOODS_1,
        TID.CURSED_WOODS_2, TID.FROGS_BURROW_RIGHT, TID.FIONAS_HOUSE_1,
        TID.FIONAS_HOUSE_2, TID.QUEENS_TOWER_600, TID.KINGS_TOWER_600,
        TID.KINGS_TOWER_1000, TID.QUEENS_TOWER_1000, TID.GUARDIA_COURT_TOWER,
        # Manoria Cathedral
        TID.MANORIA_CATHEDRAL_1, TID.MANORIA_CATHEDRAL_2,
        TID.MANORIA_CATHEDRAL_3,
        TID.MANORIA_INTERIOR_1, TID.MANORIA_INTERIOR_2,
        TID.MANORIA_INTERIOR_3, TID.MANORIA_INTERIOR_4,
        TID.MANORIA_SHRINE_SIDEROOM_1, TID.MANORIA_SHRINE_SIDEROOM_2,
        TID.MANORIA_BROMIDE_1, TID.MANORIA_BROMIDE_2,
        TID.MANORIA_BROMIDE_3,
    ]

    # TID.YAKRAS_ROOM to mid.  Vanilla mid ether
    # In standard jets TID.MANORIA_INTERIOR_3 is tiered mid

    ret_dict[td.TreasureLocTier.LOW_MID] = [
        # Magus's shrine has a speed belt (!) in vanilla.  Boost tier?
        TID.MANORIA_SHRINE_MAGUS_1, TID.MANORIA_SHRINE_MAGUS_2,
        # Heckran's Cave
        TID.HECKRAN_CAVE_SIDETRACK, TID.HECKRAN_CAVE_ENTRANCE,
        TID.HECKRAN_CAVE_1, TID.HECKRAN_CAVE_2,
        # Guardia Prison
        # Consider improving out-of-the-way chests.
        TID.PRISON_TOWER_1000, TID.GUARDIA_JAIL_FRITZ,
        TID.GUARDIA_JAIL_FRITZ_STORAGE, TID.GUARDIA_JAIL_CELL,
        TID.GUARDIA_JAIL_OMNICRONE_1, TID.GUARDIA_JAIL_OMNICRONE_2,
        TID.GUARDIA_JAIL_OMNICRONE_3, TID.GUARDIA_JAIL_HOLE_1,
        TID.GUARDIA_JAIL_HOLE_2, TID.GUARDIA_JAIL_OUTER_WALL,
        TID.GUARDIA_JAIL_OMNICRONE_4, # TID.GIANTS_CLAW_KINO_CELL,
        # Early Future
        TID.ARRIS_DOME_FOOD_STORE, TID.ARRIS_DOME_RATS,
        TID.LAB_16_1, TID.LAB_16_2, TID.LAB_16_3, TID.LAB_16_4,
        TID.LAB_32_1, TID.LAB_32_RACE_LOG,
        TID.SEWERS_1, TID.SEWERS_2, TID.SEWERS_3,
        TID.FACTORY_LEFT_AUX_CONSOLE, TID.FACTORY_LEFT_SECURITY_LEFT,
        TID.FACTORY_LEFT_SECURITY_RIGHT, TID.FACTORY_RIGHT_CRANE_LOWER,
        TID.FACTORY_RIGHT_CRANE_UPPER, TID.FACTORY_RIGHT_DATA_CORE_1,
        TID.FACTORY_RIGHT_DATA_CORE_2, TID.FACTORY_RIGHT_FLOOR_BOTTOM,
        TID.FACTORY_RIGHT_FLOOR_LEFT, TID.FACTORY_RIGHT_FLOOR_SECRET,
        TID.FACTORY_RIGHT_FLOOR_TOP, TID.FACTORY_RIGHT_INFO_ARCHIVE,
        TID.FACTORY_RUINS_GENERATOR
    ]

    ret_dict[td.TreasureLocTier.MID] = [
        # Denadoro
        TID.YAKRAS_ROOM,
        TID.DENADORO_MTS_SCREEN2_1, TID.DENADORO_MTS_SCREEN2_2,
        TID.DENADORO_MTS_SCREEN2_3, TID.DENADORO_MTS_FINAL_1,
        TID.DENADORO_MTS_FINAL_2, TID.DENADORO_MTS_FINAL_3,
        TID.DENADORO_MTS_WATERFALL_TOP_3, TID.DENADORO_MTS_WATERFALL_TOP_4,
        TID.DENADORO_MTS_WATERFALL_TOP_5, TID.DENADORO_MTS_ENTRANCE_1,
        TID.DENADORO_MTS_ENTRANCE_2, TID.DENADORO_MTS_SCREEN3_1,
        TID.DENADORO_MTS_SCREEN3_2, TID.DENADORO_MTS_SCREEN3_3,
        TID.DENADORO_MTS_SCREEN3_4, TID.DENADORO_MTS_AMBUSH,
        TID.DENADORO_MTS_SAVE_PT,
        # Castle Magus
        TID.MAGUS_CASTLE_RIGHT_HALL, TID.MAGUS_CASTLE_GUILLOTINE_1,
        TID.MAGUS_CASTLE_GUILLOTINE_2, TID.MAGUS_CASTLE_SLASH_ROOM_1,
        TID.MAGUS_CASTLE_SLASH_ROOM_2, TID.MAGUS_CASTLE_STATUE_HALL,
        TID.MAGUS_CASTLE_FOUR_KIDS, TID.MAGUS_CASTLE_OZZIE_1,
        TID.MAGUS_CASTLE_OZZIE_2, TID.MAGUS_CASTLE_ENEMY_ELEVATOR,
        # Prehistory
        TID.MYSTIC_MT_STREAM, TID.FOREST_MAZE_1, TID.FOREST_MAZE_2,
        TID.FOREST_MAZE_3, TID.FOREST_MAZE_4, TID.FOREST_MAZE_5,
        TID.FOREST_MAZE_6, TID.FOREST_MAZE_7, TID.FOREST_MAZE_8,
        TID.FOREST_MAZE_9,
        TID.DACTYL_NEST_1, TID.DACTYL_NEST_2, TID.DACTYL_NEST_3,
        TID.REPTITE_LAIR_REPTITES_1, TID.REPTITE_LAIR_REPTITES_2,
        # Tyrano Lair
        TID.TYRANO_LAIR_TRAPDOOR, TID.TYRANO_LAIR_MAZE_1,
        TID.TYRANO_LAIR_MAZE_2, TID.TYRANO_LAIR_MAZE_3,
        TID.TYRANO_LAIR_MAZE_4, TID.TYRANO_LAIR_KINO_CELL,
        TID.MAGUS_CASTLE_LEFT_HALL, TID.MAGUS_CASTLE_UNSKIPPABLES,
        TID.MAGUS_CASTLE_PIT_E, TID.MAGUS_CASTLE_PIT_NE,
        TID.MAGUS_CASTLE_PIT_NW, TID.MAGUS_CASTLE_PIT_W,
    ]

    ret_dict[td.TreasureLocTier.MID_HIGH] = [
        # Higher Tier for
        TID.DENADORO_MTS_WATERFALL_TOP_1, TID.DENADORO_MTS_WATERFALL_TOP_2,
        # Prismshard quest
        TID.GUARDIA_BASEMENT_1, TID.GUARDIA_BASEMENT_2, TID.GUARDIA_BASEMENT_3,
        TID.GUARDIA_TREASURY_1, TID.GUARDIA_TREASURY_2, TID.GUARDIA_TREASURY_3,
        # Desert
        TID.SUNKEN_DESERT_B1_NW, TID.SUNKEN_DESERT_B1_NE,
        TID.SUNKEN_DESERT_B1_SE, TID.SUNKEN_DESERT_B1_SW,
        TID.SUNKEN_DESERT_B2_NW, TID.SUNKEN_DESERT_B2_N,
        TID.SUNKEN_DESERT_B2_W,  TID.SUNKEN_DESERT_B2_SW,
        TID.SUNKEN_DESERT_B2_SE, TID.SUNKEN_DESERT_B2_E,
        TID.SUNKEN_DESERT_B2_CENTER,
        # Ozzie's Fort
        TID.OZZIES_FORT_GUILLOTINES_1, TID.OZZIES_FORT_GUILLOTINES_2,
        TID.OZZIES_FORT_GUILLOTINES_3, TID.OZZIES_FORT_GUILLOTINES_4,
        TID.OZZIES_FORT_FINAL_1, TID.OZZIES_FORT_FINAL_2,
        # Giant's Claw
        TID.GIANTS_CLAW_CAVES_1, TID.GIANTS_CLAW_CAVES_2,
        TID.GIANTS_CLAW_CAVES_3, TID.GIANTS_CLAW_CAVES_4,
        TID.GIANTS_CLAW_CAVES_5,
        # Free sealed Rooms
        TID.BANGOR_DOME_SEAL_1, TID.BANGOR_DOME_SEAL_2, TID.BANGOR_DOME_SEAL_3,
        TID.TRANN_DOME_SEAL_1, TID.TRANN_DOME_SEAL_2,
        # Death Peak
        TID.DEATH_PEAK_SOUTH_FACE_SPAWN_SAVE, TID.DEATH_PEAK_SOUTH_FACE_SUMMIT,
        TID.DEATH_PEAK_FIELD, TID.DEATH_PEAK_CAVES_LEFT,
        TID.DEATH_PEAK_CAVES_CENTER, TID.DEATH_PEAK_CAVES_RIGHT,
        TID.DEATH_PEAK_KRAKKER_PARADE,
        # Geno Dome
        TID.GENO_DOME_1F_1, TID.GENO_DOME_1F_2, TID.GENO_DOME_1F_3,
        TID.GENO_DOME_1F_4, TID.GENO_DOME_ROOM_1, TID.GENO_DOME_ROOM_2,
        TID.GENO_DOME_PROTO4_1, TID.GENO_DOME_PROTO4_2, TID.GENO_DOME_2F_1,
        TID.GENO_DOME_2F_2, TID.GENO_DOME_2F_3, TID.GENO_DOME_2F_4,
        # Most of Ocean Palace
        TID.OCEAN_PALACE_MAIN_S,
        TID.OCEAN_PALACE_MAIN_N, TID.OCEAN_PALACE_E_ROOM,
        TID.OCEAN_PALACE_W_ROOM, TID.OCEAN_PALACE_SWITCH_NW,
        TID.OCEAN_PALACE_SWITCH_SW, TID.OCEAN_PALACE_SWITCH_NE,
        # Mt. Woe
        TID.MT_WOE_2ND_SCREEN_1, TID.MT_WOE_2ND_SCREEN_2,
        TID.MT_WOE_2ND_SCREEN_3, TID.MT_WOE_2ND_SCREEN_4,
        TID.MT_WOE_2ND_SCREEN_5, TID.MT_WOE_3RD_SCREEN_1,
        TID.MT_WOE_3RD_SCREEN_2, TID.MT_WOE_3RD_SCREEN_3,
        TID.MT_WOE_3RD_SCREEN_4, TID.MT_WOE_3RD_SCREEN_5,
        TID.MT_WOE_1ST_SCREEN, TID.MT_WOE_FINAL_1,
        TID.MT_WOE_FINAL_2,
    ]

    ret_dict[td.TreasureLocTier.HIGH_AWESOME] = [
        TID.ARRIS_DOME_SEAL_1, TID.ARRIS_DOME_SEAL_2,
        TID.ARRIS_DOME_SEAL_3, TID.ARRIS_DOME_SEAL_4,
        TID.REPTITE_LAIR_SECRET_B2_NE_RIGHT, TID.REPTITE_LAIR_SECRET_B1_SW,
        TID.REPTITE_LAIR_SECRET_B1_NE, TID.REPTITE_LAIR_SECRET_B1_SE,
        TID.REPTITE_LAIR_SECRET_B2_SE_RIGHT,
        TID.REPTITE_LAIR_SECRET_B2_NE_OR_SE_LEFT,
        TID.REPTITE_LAIR_SECRET_B2_SW,
        TID.BLACK_OMEN_AUX_COMMAND_MID,
        TID.BLACK_OMEN_AUX_COMMAND_NE, TID.BLACK_OMEN_GRAND_HALL,
        TID.BLACK_OMEN_NU_HALL_NW, TID.BLACK_OMEN_NU_HALL_W,
        TID.BLACK_OMEN_NU_HALL_SW, TID.BLACK_OMEN_NU_HALL_NE,
        TID.BLACK_OMEN_NU_HALL_E, TID.BLACK_OMEN_NU_HALL_SE,
        TID.BLACK_OMEN_ROYAL_PATH, TID.BLACK_OMEN_RUMINATOR_PARADE,
        TID.BLACK_OMEN_EYEBALL_HALL, TID.BLACK_OMEN_TUBSTER_FLY,
        TID.BLACK_OMEN_MARTELLO, TID.BLACK_OMEN_ALIEN_SW,
        TID.BLACK_OMEN_ALIEN_NE, TID.BLACK_OMEN_ALIEN_NW,
        TID.BLACK_OMEN_TERRA_W, TID.BLACK_OMEN_TERRA_NE,
        # Copying standard for these two ocean palace chests
        TID.OCEAN_PALACE_SWITCH_SECRET, TID.OCEAN_PALACE_FINAL,
    ]

    ret_dict[td.TreasureLocTier.SEALED] = [
        TID.NORTHERN_RUINS_ANTECHAMBER_LEFT_600,
        TID.NORTHERN_RUINS_ANTECHAMBER_SEALED_600,
        TID.NORTHERN_RUINS_ANTECHAMBER_LEFT_1000,
        TID.NORTHERN_RUINS_ANTECHAMBER_SEALED_1000,
        TID.NORTHERN_RUINS_BACK_LEFT_SEALED_600,
        TID.NORTHERN_RUINS_BACK_LEFT_SEALED_1000,
        TID.NORTHERN_RUINS_BACK_RIGHT_SEALED_600,
        TID.NORTHERN_RUINS_BACK_RIGHT_SEALED_1000,
        TID.NORTHERN_RUINS_BASEMENT_600,
        TID.NORTHERN_RUINS_BASEMENT_1000,
        TID.TRUCE_INN_SEALED_600, TID.TRUCE_INN_SEALED_1000,
        TID.PORRE_ELDER_SEALED_1, TID.PORRE_ELDER_SEALED_2,
        TID.PORRE_MAYOR_SEALED_1, TID.PORRE_MAYOR_SEALED_2,
        TID.GUARDIA_CASTLE_SEALED_600, TID.GUARDIA_CASTLE_SEALED_1000,
        TID.GUARDIA_FOREST_SEALED_600, TID.GUARDIA_FOREST_SEALED_1000,
        TID.HECKRAN_SEALED_1, TID.HECKRAN_SEALED_2,
        TID.PYRAMID_LEFT, TID.PYRAMID_RIGHT,
        TID.MAGIC_CAVE_SEALED,
    ]

    return ret_dict
